version: "3.7"

# This file can be use for local development of the updater script
# so no need to install Python
# Can be run like:
# $ docker-compose -f docker-compose.dev.yml run dev sh
# All the changes made to `updater.py` outside of Docker, will be reflected inside the container
services:
  dev:
    image: python:3.9-alpine
    env_file: .env
    environment:
      # So stdout can be viewed through docker logs
      - PYTHONUNBUFFERED=0
    volumes:
      - ./app:/app
    working_dir: /app
